### PR TITLE
[CI] Test against Ruby 2.x

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by nicolasleger** [comment]
Tests already fail on Ruby `2.1` which is `eol`.
I propose to drop support of it.

**Comment by schneems** [comment]
That’s fine, can you clear out 2.1?

**Comment by nicolasleger** [comment]
Sure, done!

**Comment by nicolasleger** [comment]
All tests pass on my fork at https://travis-ci.org/nicolasleger/pg_lock/builds/343402633
You might restart the failing job.

**Comment by schneems** [comment]
Thanks!

**Pull request merged**
